name: PutgeJSDelivrCache

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: tests

jobs:
  purge_js:
    runs-on: alpine
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://purge.jsdelivr.net/gh/aoliverwd/setting-card-component@main/dist/settings-card.min.js